# Generated by Django 4.2.1 on 2023-05-31 19:01

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('blog', '0009_alter_comment_post'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='saved',
            field=models.ManyToManyField(related_name='saved_posts', to=settings.AUTH_USER_MODEL),
        ),
    ]
